feat: voice channel groups
discordjs/voice pull request #147
Opened 2021-06-28 18:51 UTC by amishshah

**Please describe the changes this PR makes and why it should be merged:**

Resolves #144.

VoiceConnections are now stored in a 2D map (`{group_id -> {guild_id -> voice_connection}}`).

The default global group ID is `default` - this is so the update is backwards compatible. Users may optionally specify their own group ID, e.g. the client ID, when creating their voice connections if they wish to run more than one bot in the process.

Also exposes two new methods:

- `DataStore#getGroups()` - get the full 2D group map
- `DataStore#getVoiceConnections(group = 'default')` - gets the map of guild IDs to voice connections for the given group

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- This PR changes the library's interface (methods or parameters added)

2021-06-28 22:27 UTC, kyranet requested changes
Refactored those lines to avoid useless allocations (`get`ting and `delete`ing from an empty map).

You'll be able to remove `getVoiceConnections` with those two refactors, but that's up to you.

And there are uncovered lines too :eyes:

2021-06-28 22:27 UTC, kyranet commented on src/DataStore.ts
> +	return getVoiceConnections(group).get(guildId);
```suggestion
	return groups.get(group)?.get(guildId);
```

2021-06-28 22:27 UTC, kyranet commented on src/DataStore.ts
> +	return getVoiceConnections(voiceConnection.joinConfig.group)!.delete(voiceConnection.joinConfig.guildId);
```suggestion
	return groups.get(voiceConnection.joinConfig.group)?.delete(voiceConnection.joinConfig.guildId);
```

2021-06-29 20:12 UTC, SpaceEEC approved these changes
Tests and @kyranet's comments aside, LGTM

2021-06-30 09:18 UTC, vladfrangu approved these changes
As space said, other than kyras comments, LGTM!

2021-07-12 09:17 UTC, merged