message and interaction event updated in examples
discordjs/voice pull request #159
Opened 2021-07-22 07:10 UTC by killer069

**Please describe the changes this PR makes and why it should be merged:**

Examples contained depreciated message and interaction event listeners. So I updated them.

**Status and versioning classification:**

2021-07-22 07:29 UTC, SuperchupuDev approved these changes

2021-07-24 14:10 UTC, amishshah requested changes
Looks good, except one change for the wait function

2021-07-24 14:10 UTC, amishshah commented on examples/music-bot/src/music/subscription.ts
> +	return new Promise((resolve) => setTimeout(resolve, time, 'Success').unref());
Could you replace this entire function with something like:

```ts
const { promisify } = require('util');
const wait = promisify(setTimeout);
```

Don't worry about the unref

2021-07-25 10:13 UTC, kyranet approved these changes

2021-07-25 11:02 UTC, amishshah approved these changes

2021-07-25 11:03 UTC, merged