refactor(DataStore): hook into WebSocketManager
discordjs/voice pull request #16
Opened 2021-02-03 22:54 UTC by amishshah

Resolves #15.

It is cleaner to listen to the specific `VOICE_SERVER_UPDATE` and `VOICE_STATE_UPDATE` packets from the Discord.js WebSocketManager as opposed to listening to the `raw` event from the main client and filtering the packets.

2021-02-03 23:10 UTC, SpaceEEC requested changes

2021-02-03 23:10 UTC, SpaceEEC commented on src/DataStore.ts
> +import { Client, Guild } from 'discord.js';
We actually export a `WSEvent` object as part of `Constants`.
```suggestion
import { Client, Constants, Guild } from 'discord.js';
```

2021-02-03 23:10 UTC, SpaceEEC commented on src/DataStore.ts
> +	client.ws.on('VOICE_SERVER_UPDATE', (payload: GatewayVoiceServerUpdate) => {
```suggestion
	client.ws.on(Constants.WSEvents.VOICE_SERVER_UPDATE, (payload: GatewayVoiceServerUpdate) => {
```

2021-02-03 23:10 UTC, SpaceEEC commented on src/DataStore.ts
> +	client.ws.on('VOICE_STATE_UPDATE', (payload: GatewayVoiceState) => {
```suggestion
	client.ws.on(Constants.WSEvents.VOICE_STATE_UPDATE, (payload: GatewayVoiceState) => {
```

2021-02-04 11:13 UTC, kyranet approved these changes

2021-02-04 11:28 UTC, SpaceEEC approved these changes

2021-02-04 15:37 UTC, merged