fix(Examples): destroy discord.js v12 adapter less readily
discordjs/voice pull request #160
Opened 2021-07-24 10:35 UTC by amishshah

**Please describe the changes this PR makes and why it should be merged:**

Adjusts the discord.js v12 adapter to match the same destroy conditions given by the adapter provided with discord.js v13.

Resolves #153 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes

2021-07-24 10:53 UTC, SpaceEEC commented on examples/basic/adapter.ts
> +		trackedShards.set(shardID, new Set());
Why not delete the set instead of replacing it?

2021-07-24 11:47 UTC, SpaceEEC approved these changes

2021-07-24 16:44 UTC, iCrawl approved these changes

2021-07-25 10:15 UTC, kyranet requested changes

2021-07-25 10:15 UTC, kyranet commented on examples/basic/adapter.ts
> +	client.on(Constants.Events.SHARD_DISCONNECT, (_, shardID) => {
If you're going to call the guild's ID with `Id` (see line 26), then change this to `shardId`, otherwise rename the variable below to `guildID`.

2021-07-25 11:00 UTC, kyranet approved these changes

2021-07-25 11:04 UTC, merged