chore: update examples for v13
discordjs/voice pull request #174
Opened 2021-08-09 19:26 UTC by Fyko

**Please describe the changes this PR makes and why it should be merged:**
This PR updates examples for Discord.js v13. Additionally, it fixes a [documentation error](https://github.com/discordjs/voice/commit/84c267829b9302c7da0cf5b973165e5307f175dc#diff-c8b39ef66dfab8b1d90c475e891dc6c9af4fb87e8002cf4c18aff7afb3d91a6b). 

Closes #170.

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-08-10 05:27 UTC, killer069 requested changes
Maybe add some check mechanism instead of setting guild commands again and again.

2021-08-10 05:27 UTC, killer069 commented on examples/music-bot/src/bot.ts
> +		await devGuild.commands.set([
It would be great to have some check if the commands are already present in the guild before setting commands again and again on each start of bot.

2021-08-11 04:55 UTC, DaStormer commented on examples/music-bot/src/bot.ts
> +const client = new Client({ intents: ['GUILD_VOICE_STATES', 'GUILD_MESSAGES', 'GUILDS'] });
```suggestion
const client = new Client({ intents: ['GUILD_VOICE_STATES', 'GUILDS'] });
```
`GUILD_MESSAGES` intent isn't needed

2021-09-11 12:42 UTC, amishshah commented
@Fyko could you remove the unnecessary intent mentioned above and also move command deployment to its own script that can be run separately?

2021-12-24 12:58 UTC, imranbarbhuiya commented
Why it's not getting merged?

2022-10-20 03:41 UTC, closed without merging