Include StreamType enum description in new docs
discordjs/voice pull request #239
Opened 2021-12-02 15:56 UTC by RanAwaySuccessfully

**Please describe the changes this PR makes and why it should be merged:**

https://discord.js.org/#/docs/voice/stable/typedef/StreamType

The link above does not have a description for the StreamType enum. This pull request should _hopefully_ include them.

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
- Code changes ~~have been tested against the Discord API~~, or there are no code changes

2021-12-02 16:03 UTC, SpaceEEC approved these changes
They are included now 🎉

2021-12-02 17:00 UTC, kyranet approved these changes

2021-12-02 17:03 UTC, kyranet requested changes
Didn't render the characters to me, but apparently there were some trailing tabs, which caused ESLint to complain 😅

Those suggested changes fix them 👍🏼

2021-12-02 17:03 UTC, kyranet commented on src/audio/TransformerGraph.ts
> +
```suggestion

```

2021-12-02 17:03 UTC, kyranet commented on src/audio/TransformerGraph.ts
> +
```suggestion

```

2021-12-02 17:03 UTC, kyranet commented on src/audio/TransformerGraph.ts
> +
```suggestion

```

2021-12-02 17:03 UTC, kyranet commented on src/audio/TransformerGraph.ts
> +
```suggestion

```

2021-12-03 01:55 UTC, kyranet approved these changes
Everything looking good now!

2021-12-06 08:01 UTC, iCrawl approved these changes

2021-12-06 08:01 UTC, merged